package simpledb;

import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends Operator {

    private static final long serialVersionUID = 1L;
    JoinPredicate predicate;
    OpIterator child1;
    OpIterator child2;
    ArrayList<Tuple> tlist;
    Iterator<Tuple> it;

    /**
     * Constructor. Accepts two children to join and the predicate to join them
     * on
     * 
     * @param p
     *            The predicate to use to join the children
     * @param child1
     *            Iterator for the left(outer) relation to join
     * @param child2
     *            Iterator for the right(inner) relation to join
     */
    public Join(JoinPredicate p, OpIterator child1, OpIterator child2) {
        this.predicate = p;
        this.child1 = child1;
        this.child2 = child2;
    }

    public JoinPredicate getJoinPredicate() {
        return predicate;
    }

    /**
     * @return
     *       the field name of join field1. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField1Name() {
        int fieldnum1 = predicate.getField1();
        return child1.getTupleDesc().getFieldName(fieldnum1);
    }

    /**
     * @return
     *       the field name of join field2. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField2Name() {
        int fieldnum2 = predicate.getField2();
        return child2.getTupleDesc().getFieldName(fieldnum2);
    }

    /**
     * @see simpledb.TupleDesc#merge(TupleDesc, TupleDesc) for possible
     *      implementation logic.
     */
    public TupleDesc getTupleDesc() {
        TupleDesc td1 = child1.getTupleDesc();
        TupleDesc td2 = child2.getTupleDesc();
        return TupleDesc.merge(td1,td2);
    }

    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        child1.open();
        child2.open();
        super.open();

        child1.rewind();
        child2.rewind();

        if (this.tlist != null) {
            it = this.tlist.iterator();
            return;
        }

        this.tlist = new ArrayList<Tuple>();
        while (child1.hasNext()) {
            Tuple t1 = child1.next();
            while (child2.hasNext()) {
                Tuple t2 = child2.next();
                if (!predicate.filter(t1, t2))
                    continue;

                Tuple t = Tuple.merge(t1, t2);
                this.tlist.add(t);

            } // inner loop end

            child2.rewind();
        } // outer loop end

        this.it = tlist.iterator();
    }

    public void close() {
        super.close();
        child1.close();
        child2.close();
        it = null;
    }

    public void rewind() throws DbException, TransactionAbortedException {
        close();
        open();
    }

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, if an equality predicate is used there will be two
     * copies of the join attribute in the results. (Removing such duplicate
     * columns can be done with an additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     * 
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        if (it == null)
            throw new DbException("Iterator not initialized");

        if (it.hasNext())
            return it.next();
        else
            return null;
    }

    @Override
    public OpIterator[] getChildren() {
        return new OpIterator[] { this.child1, this.child2 };
    }

    @Override
    public void setChildren(OpIterator[] children) {
        this.child1 = children[0];
        this.child2 = children[1];
    }

}
